name: zarrcade
channels:
  - conda-forge
dependencies:
  - fastapi
  - fsspec
  - jinja2
  - loguru
  - python=3.10
  - s3fs
  - uvicorn
  - zarr
  - tornado
  - pillow
  - pandas
  - sqlalchemy
  - sqlite
  - ipykernel
  - pydantic
  - pydantic-settings
